modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/herd-mentality/issues"
license="LGPL v2.1"

[[mods]]
modId="herdmentality"
updateJSONURL="https://updates.blamejared.com/get?n=herdmentality&gv=1.16.3"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.herdmentality]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.herdmentality]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="SERVER"
    
[[dependencies.herdmentality]]
    modId="bookshelf"
    mandatory=true
    versionRange="[6,)"
    ordering="AFTER"
    side="BOTH"