modLoader="javafml"
loaderVersion="[36,]"
issueTrackerURL="https://github.com/Darkhax-Minecraft/herd-mentality/issues"
license="LGPL v2.1"

[[mods]]
modId="herdmentality"
updateJSONURL="https://updates.blamejared.com/get?n=herdmentality&gv=1.16.5"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''
    
[[dependencies.herdmentality]]
    modId="bookshelf"
    mandatory=true
    versionRange="[10,)"
    ordering="AFTER"
    side="BOTH"